os:
  - linux
  - osx

language: clojure

jdk:
  - oraclejdk11

matrix:
  include:
    - jdk: openjdk11
      before_install:
        - sudo rm "${JAVA_HOME}/lib/security/cacerts"
        - sudo ln -s /etc/ssl/certs/java/cacerts "${JAVA_HOME}/lib/security/cacerts"

install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get install libxkbfile-dev; fi
  - nvm install 10
  - nvm use 10
  - npm install -g shadow-cljs

script: make release
